package modelo;

import java.sql.Timestamp;

/**
 * Reuniones generated by hbm2java
 */
public class Reuniones implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer idReunion;
    private Users usersByProfesorId;
    private Users usersByAlumnoId;
    private String estado;
    private String estadoEus;
    private String idCentro;
    private String titulo;
    private String asunto;
    private String aula;
    private Timestamp fecha;

    public Reuniones() {
    }



    public Reuniones(Users usersByProfesorId, Users usersByAlumnoId, String estado, String estadoEus, String idCentro,
                     String titulo, String asunto, String aula, Timestamp fecha) {
        this.usersByProfesorId = usersByProfesorId;
        this.usersByAlumnoId = usersByAlumnoId;
        this.estado = estado;
        this.estadoEus = estadoEus;
        this.idCentro = idCentro;
        this.titulo = titulo;
        this.asunto = asunto;
        this.aula = aula;
        this.fecha = fecha;
    }

    public Integer getIdReunion() {
        return this.idReunion;
    }

    public void setIdReunion(Integer idReunion) {
        this.idReunion = idReunion;
    }

    public Users getUsersByProfesorId() {
        return this.usersByProfesorId;
    }

    public void setUsersByProfesorId(Users usersByProfesorId) {
        this.usersByProfesorId = usersByProfesorId;
    }

    public Users getUsersByAlumnoId() {
        return this.usersByAlumnoId;
    }

    public void setUsersByAlumnoId(Users usersByAlumnoId) {
        this.usersByAlumnoId = usersByAlumnoId;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getEstadoEus() {
        return this.estadoEus;
    }

    public void setEstadoEus(String estadoEus) {
        this.estadoEus = estadoEus;
    }

    public String getIdCentro() {
        return this.idCentro;
    }

    public void setIdCentro(String idCentro) {
        this.idCentro = idCentro;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getAsunto() {
        return this.asunto;
    }

    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }

    public String getAula() {
        return this.aula;
    }

    public void setAula(String aula) {
        this.aula = aula;
    }

    public Timestamp getFecha() {
        return this.fecha;
    }

    public void setFecha(Timestamp fecha) {
        this.fecha = fecha;
    }


    @Override
    public String toString() {
        return "Reuniones{" +
                "idReunion=" + idReunion +
                ", usersByProfesorId=" + usersByProfesorId +
                ", usersByAlumnoId=" + usersByAlumnoId +
                ", estado='" + estado + '\'' +
                ", estadoEus='" + estadoEus + '\'' +
                ", idCentro='" + idCentro + '\'' +
                ", titulo='" + titulo + '\'' +
                ", asunto='" + asunto + '\'' +
                ", aula='" + aula + '\'' +
                ", fecha=" + fecha +
                '}';
    }

    private String ponerEstado(String estado) {
        // TODO Auto-generated method stub

        if (estado.equalsIgnoreCase("pendiente")) {
            estado = "-P";
        } else if (estado.equalsIgnoreCase("aceptada")) {
            estado = "-C";
        } else if (estado.equalsIgnoreCase("denegada")) {
            estado = "-R";
        } else if (estado.equalsIgnoreCase("conflicto")) {
            estado = "-E";
        }
        return estado;
    }

    private int consegiorHora(int hora) {
        // TODO Auto-generated method stub
        if (hora == 8) {
            hora = 0;
        } else if (hora == 9) {
            hora = 1;
        } else if (hora == 10) {
            hora = 2;
        } else if (hora == 11) {
            hora = 3;
        } else if (hora == 12) {
            hora = 4;
        }
        return hora;
    }



}
