package modelo;
// Generated 29 ene 2025, 8:10:48 by Hibernate Tools 6.5.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 * Ciclos generated by hbm2java
 */
public class Ciclos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String nombre;
	private Set<Object> matriculacioneses = new HashSet<Object>(0);
	private Set<Object> moduloses = new HashSet<Object>(0);

	public Ciclos() {
	}

	public Ciclos(int id) {
		this.id = id;
	}

	public Ciclos(int id, String nombre, Set<Object> matriculacioneses, Set<Object> moduloses) {
		this.id = id;
		this.nombre = nombre;
		this.matriculacioneses = matriculacioneses;
		this.moduloses = moduloses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Object> getMatriculacioneses() {
		return this.matriculacioneses;
	}

	public void setMatriculacioneses(Set<Object> matriculacioneses) {
		this.matriculacioneses = matriculacioneses;
	}

	public Set<Object> getModuloses() {
		return this.moduloses;
	}

	public void setModuloses(Set<Object> moduloses) {
		this.moduloses = moduloses;
	}

	public ArrayList<Ciclos> getCiclos() {
		// TODO Auto-generated method stub
			SessionFactory sesion = HibernateUtil.getSessionFactory();
			Session session = sesion.openSession();
			String hql = "from Ciclos";
			Query q = session.createQuery(hql);
			List<?> filas = q.list();


			return (ArrayList<Ciclos>) filas;
		
	}

}
